# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('sgr', ['core','internet','leo-satellite','point-to-point','network','mobility'])
    module.includes='.'
    module.source = [
        'model/satellite-global-routing.cc',
        #'helper/satellite-global-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('sgr')
    module_test.source = [
        'test/sgr-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'sgr'
    headers.source = [
        'model/satellite-global-routing.h',
        #'helper/satellite-global-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

